# .github/workflows
name: AndroidBuild

on: [pull_request,push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Send Build Result
        continueOnError: true
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          message: |
            Build + ${{ job.status }} at ${{ github.repository }} pushed by ${{ github.actor }}.