# .github/workflows
name: AndroidBuild

on: [pull_request,push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

#      - name: Run Tests
#        run: ./gradlew test
#
#      - name: Build Project
#        run: ./gradlew assemble

      - name: Send Build Result
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO}}
          token: ${{ secrets.TELEGRAM_TOKEN}}
          message: |
            Build ${{ job.status }} at ${{ github.repository }} with commit: ${{github.sha}} pushed by ${{ github.actor }}.
          photo: Image/yay.jpg
#            {{ if eq(job.status, 'success') }}
#            {{ else }} ./sad.jpeg